name: Upgrade dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    strategy:
      matrix:
        node-version: [20.x]

    name: Upgrade all dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "NODE_VERSION=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: yarn ci
      - run: yarn upgrade --latest # Upgrade dependencies to their latest version
      - run: rimraf node_modules yarn-lock.json
      - run: yarn install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "build: upgrade dependencies to the latest version"
          title: Upgrade dependencies to the latest version
